version: "3"
services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbitmq-docker
    volumes:
      - /home/cgi/docker-volume:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    ports:
      # The standard AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
  producer:
    build: ./producer/
    container_name: rabbitMQ-producer
    ports:
      - 8010:8010

  consumer:
    build: ./consumer/
    container_name: rabbitMQ-consumer
    ports:
      - 8020:8020