version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    volumes:
      - /home/cgi/docker-volume:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    hostname: localhost
    network_mode: host

  producer:
    build: ./producer/
    container_name: rabbitMQ-producer
    ports:
      - 8010:8010
    depends_on:
      - rabbitmq
    restart: always
    expose:
      - 8010
    hostname: localhost
    network_mode: host


  consumer:
    build: ./consumer/
    container_name: rabbitMQ-consumer
    ports:
      - 8020:8020
    depends_on:
      - rabbitmq
    restart: always
    expose:
      - 8020
    hostname: localhost
    network_mode: host