version: "3"
services:
  producer:
    image: neo4j
    container_name: neo4j-springboot
    volumes:
      - /home/cgi/docker-volume:/data
    ports:
      - 7474:7474
      - 7687:7687

  consumer:
    build: .
    container_name: movie-critic
    ports:
      - 8060:8080
    depends_on:
      - neo4jdb
    expose:
      - 8060